language: go
go:
  - 1.9.2
env:
  - NGT_VERSION=1.2.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake
  - cd /tmp
  - wget -q https://github.com/yahoojapan/NGT/archive/v${NGT_VERSION}.zip
  - unzip v${NGT_VERSION}.zip
  - cd NGT-${NGT_VERSION}
  - mkdir build
  - cd build && cmake .. && make && sudo make install
  - cd ${TRAVIS_BUILD_DIR}
script:
  - go test -v ./...
